model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.ICIP_NonVQModel # Using U-net
  params: 
    image_key: concat_input
    refine_mode: True
    embed_dim: 256
    n_embed: 1024
    concat_input: True
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 4 # masked image  + binary_mask
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16] 
      dropout: 0.0


    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 50001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.sun_comp.Sun360CompTrain
      params:
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: True
          no_rescale: False
    validation:
      target: taming.data.sun_comp.Sun360CompValidation
      params:
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: True
          no_rescale: False
