model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params: 
    image_key: concat_input # `concat_input` when VQGAN_1(condition-stage), `image` when VQGAN_2
    embed_dim: 256
    n_embed: 1024
    concat_input: True # True when VQGAN_1(condition-stage), False when VQGAN_2
    completion: False # Switch to True if you train vqgan with completion. False for our paper setting.
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 7 # ch of concat_input: image + coord + binary_mask. Set as 7 when VQGAN_1(condition-stage), 3 when VQGAN_2
      out_ch: 7 # Set as 7 when VQGAN_1(condition-stage), 3 when VQGAN_2
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 50001
        disc_weight: 0.8
        codebook_weight: 1.0
        spherical_perceptual: True

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: taming.data.sun_comp.Sun360CompTrain
      params:
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: False
          no_rescale: False
    validation:
      target: taming.data.sun_comp.Sun360CompValidation
      params:
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: False
          no_rescale: False
